//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicWrap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicWrap.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive URL:.
        /// </summary>
        public static string AddComic_ArchiveUrl {
            get {
                return ResourceManager.GetString("AddComic_ArchiveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page URL:.
        /// </summary>
        public static string AddComic_CurrentUrl {
            get {
                return ResourceManager.GetString("AddComic_CurrentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is invalid..
        /// </summary>
        public static string AddComic_Error_InvalidUrl {
            get {
                return ResourceManager.GetString("AddComic_Error_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Comic.
        /// </summary>
        public static string AddComic_Title {
            get {
                return ResourceManager.GetString("AddComic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Alert_Error_Title {
            get {
                return ResourceManager.GetString("Alert_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Alert_Generic_Confirm {
            get {
                return ResourceManager.GetString("Alert_Generic_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Comic: {0}.
        /// </summary>
        public static string ComicDetail_DeletedComic {
            get {
                return ResourceManager.GetString("ComicDetail_DeletedComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComicDetail_Options_Cancel {
            get {
                return ResourceManager.GetString("ComicDetail_Options_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ComicDetail_Options_Delete {
            get {
                return ResourceManager.GetString("ComicDetail_Options_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Options.
        /// </summary>
        public static string ComicDetail_Options_Title {
            get {
                return ResourceManager.GetString("ComicDetail_Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0} days ago.
        /// </summary>
        public static string ComicInfo_LastUpdated {
            get {
                return ResourceManager.GetString("ComicInfo_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string ComicInfo_LastUpdatedShort {
            get {
                return ResourceManager.GetString("ComicInfo_LastUpdatedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ComicReader_More_Cancel {
            get {
                return ResourceManager.GetString("ComicReader_More_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Cover Page.
        /// </summary>
        public static string ComicReader_More_SetAsCover {
            get {
                return ResourceManager.GetString("ComicReader_More_SetAsCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Options.
        /// </summary>
        public static string ComicReader_More_Title {
            get {
                return ResourceManager.GetString("ComicReader_More_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Home_Subtitle_Library {
            get {
                return ResourceManager.GetString("Home_Subtitle_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Home_Subtitle_Updates {
            get {
                return ResourceManager.GetString("Home_Subtitle_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComicWrap.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover image has finished downloading.
        /// </summary>
        public static string ImageDownload_Complete_Msg {
            get {
                return ResourceManager.GetString("ImageDownload_Complete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        public static string ImageDownload_Complete_Title {
            get {
                return ResourceManager.GetString("ImageDownload_Complete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL was found. Download has started, please wait for download completion..
        /// </summary>
        public static string ImageDownload_FoundUrl_Msg {
            get {
                return ResourceManager.GetString("ImageDownload_FoundUrl_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located Image URL.
        /// </summary>
        public static string ImageDownload_FoundUrl_Title {
            get {
                return ResourceManager.GetString("ImageDownload_FoundUrl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate image URL.
        /// </summary>
        public static string ImageDownload_LocateError_Msg {
            get {
                return ResourceManager.GetString("ImageDownload_LocateError_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Theme_System {
            get {
                return ResourceManager.GetString("Settings_Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Title_Appearance {
            get {
                return ResourceManager.GetString("Settings_Title_Appearance", resourceCulture);
            }
        }
    }
}
